# This Docker Compose file is designed to set up a development environment with a Node.js
# service that communicates with a PostgreSQL database. The Node.js service is configured
# to connect to the database using environment variables, and the database service is initialized
# with a custom SQL script during its first run. The network mode allows seamless communication
# between the two services.

version: "3.8" # Specifies the version of the Compose file format.

services:
    # Defines the 'node' service
    node:
        image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye # Dockerfile to use for building the image.

        # Mounts the parent directory of the current directory to /workspaces in the container.
        # 'cached' improves performance for macOS.
        volumes:
            - ../..:/workspaces:cached

        command: sleep infinity # Overrides the default command to keep the container running indefinitely.
        environment: # Environment variables for the mongodb service
            MONGO_HOST: "mongodb:27017" #${MONGO_HOST}
            MONGO_URI: "mongodb://root:example@mongodb:27017/mydatabase"
            MONGO_USER: root
            MONGO_PWD: example

    # MongoDB service
    mongodb:
        image: mongo #uses mongodb latest version from Docker Hub
        container_name: mongodb
        ports:
            - "27017:27017" # Expose MongoDB on port 27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "example"
            MONGO_INITDB_DATABASE: "mydatabase"

# Volumes to persist on  MongoDB data
volumes:
    mongodb-data:
